kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text={"_links":{"self":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage","templated":false},"health":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/health","templated":false},"health-path":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/health/{*path}","templated":true},"info":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/info","templated":false},"metrics-requiredMetricName":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/metrics/{requiredMetricName}","templated":true},"metrics":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/metrics","templated":false}}}"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
  - name: bar-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text={"_links":{"self":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage","templated":false},"health":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/health","templated":false},"health-path":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/health/{*path}","templated":true},"info":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/info","templated":false},"metrics-requiredMetricName":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/metrics/{requiredMetricName}","templated":true},"metrics":{"href":"https://rptsvc-qaautocand.sc25k8scl01.cksdc25.c.eu-de-1.cloud.sap/manage/metrics","templated":false}}}"
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/foo/manage"
        backend:
          service:
            name: foo-service
            port:
              number: 5678
      - pathType: Prefix
        path: "/bar/manage"
        backend:
          service:
            name: bar-service
            port:
              number: 5678
---
